
# Name and description
name: Guillaume Mestdagh
description: Modélisation, contrôle optimal, optimisation numérique
description_en: Modeling, optimal control, numerical optimization

# Photo
#avatar: https://robohash.org/gmestdagh
avatar: "/assets/portrait.jpeg"

# Includes an icon in the footer for each username you enter
footer-links:
  email:
  github: gmestdagh
  linkedin:
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  

# Technical
baseurl: "" # the subpath of your site, e.g. /blog
url: "gmestdagh.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
